lib/sdk/lib/ros_sdk/sdk.rb
This solves the annoying deprecation warnings reported in #23
=> [Chore] Clear deprecation warning

config/deployments/gcp.yml
Hi Rob/Duan
Please review GCP config file added.
=> GCP config added to ROS

lib/core/app/validators/json_schema_validator.rb, lib/core/config/locales/en.yml
Will show those handy messages for invalid `display_properties` definition:
- `display_properties - does not match specified schema: 'button' property is invalid` - if property  does not match requirements, or not specified in schema
- `display_properties - does not match specified schema: missing_keys: title` - if required property is missing
=> [PW-682] Improve JSON schema error message

lib/sdk/lib/ros_sdk/models/organization.rb
We need to query for this class_name on the `services/reward/app/models/entity.rb` at whistler side.
=> Add Org model to organization sdk file

services/iam/Gemfile.lock, services/iam/app/models/tenant.rb, services/iam/app/resources/tenant_resource.rb, services/iam/spec/factories/tenants.rb, services/iam/spec/requests/tenants_spec.rb
=> [PW-715] Activate Iam::Tenant properties"

config/deployments/gcp.yml
=> Update to gcp.yml config

services/organization/spec/dummy/bin/spring
- Add missing `spec/dummy/bin/spring` file to organization service
Circle CI was failing to build due to a missing file. This PR will add that
=> Add missing spring file to organization

lib/core/app/controllers/concerns/ros/application_controller_concern.rb, services/iam/app/controllers/devise/application_controller.rb, services/iam/app/controllers/users/sessions_controller.rb, services/iam/spec/factories/tenants.rb, services/iam/spec/requests/users/authentication_spec.rb
[Deprecation warning when running ros](https://github.com/rails-on-services/ros/issues/23)
- Added possibility to sign_in users with :alias attribute, which belongs to tenant's schema
- Added single resource wrapper for single records
- Fixed specs
=> [PW-1350]IAM users login with alias

.github/PULL_REQUEST_TEMPLATE.md
- update http link on PR template
Developers can just change the issue number instead of needing to visit Jira to copy paste the issue link.
=> Update http link on PR template

services/cognito/db/seeds/development/tenants.seeds.rb, services/comm/db/seeds/development/tenants.seeds.rb, services/iam/db/seeds/development/tenants.seeds.rb, services/organization/db/seeds/development/tenants.seeds.rb, services/storage/db/seeds/development/tenants.seeds.rb
[https://perxtechnologies.atlassian.net/browse/PW-1317](https://perxtechnologies.atlassian.net/browse/PW-1317)
`rails db:seed` generates 6 tenants now and populates it with the data.
Tenants are verticals:
* 111_111_111 is for Platform (alias `perx`)
* 222_222_222 is for Generic (alias `generic`)
* 333_333_333 is for Banking (alias `banking`)
* 444_444_444 is for Telco (alias `telco`)
* 555_555_555 is for Insurance (alias `insurance`)
* 666_666_666 is for Retail (alias `retail`)
We will have a ready to use sales demo data
=> [PW-1317] contextual seeds

services/organization/app/resources/org_resource.rb
[Filter Organization by name](https://perxtechnologies.atlassian.net/browse/PW-1270)
- Add filter to `orgs` resource on `organization` service. Filter with partial matching and case insensitive.
We're able to filter organizations by name like:
`GET /organization/orgs?filter%5Bname%5D=string`
=> [PW-1270] Implement filtering organization by name, with partial matching

services/comm/db/seeds/development/tenants.seeds.rb, services/iam/db/seeds/development/users.seeds.rb
comm tenant seed shouldn't fail now
=> [hotfix] comm tenant seed fixed

lib/core/spec/support/helpers/json_api_helper.rb
[Create spec helper method to build post json api data with nested resources](https://perxtechnologies.atlassian.net/browse/PW-1656)
- Create jsonapi_data_with_nested_resources method to handle request specs with nested resources
The `jsonapi_data` method doesn't support post request with nested resources(eg. campaign entity can be created with possible_outcomes, limits, comms). This PR creates a new method that does that.
=> [PW-1656] Create spec helper method to build post json api data with nested resources

lib/core/spec/support/helpers/json_api_helper.rb
- No Ticket
- this method's functionality has been overwritten by `jsonapi_data` improved flexibility.
Remove extra unnecessary code
=> [Hotfix] removed unecessary helper method

lib/core/lib/ros/cloudevents/fluentd_avro_logger.rb, lib/core/lib/tasks/avro.rake
[Create a rake task to register all avro schema with schema registry](https://perxtechnologies.atlassian.net/browse/PW-1836)
Rake task search for all `*.avsc` (Avro schema) files in the `./doc/schemas` and send it to registry.
Usage (within service):
```bash
rails app:ros:avro:register
```
=> [PW-1836] Avro register rake task

lib/core/lib/tasks/avro.rake
- Added check for whether the event_logging is enabled before register the schemas.
=> Skip register avro schemas if event_logging is not enabled

lib/core/app/jobs/ros/application_job.rb
* No ticket
Call `tenant.set_role_credential` from `before_perform` callback on `ApplicationJob`
Now we can make external service calls from the job.
=> add before_perform callback to the base application job

lib/core/app/jobs/ros/application_job.rb, lib/core/app/jobs/ros/platform_consumer_event_job.rb, lib/core/app/jobs/ros/platform_producer_event_job.rb, lib/core/app/jobs/ros/stream_cloud_event_job.rb, lib/core/app/jobs/ros/tenant_producer_event_job.rb, services/cognito/config/sidekiq.yml, services/comm/app/jobs/call_job.rb, services/comm/app/jobs/event_job.rb, services/comm/app/jobs/message_job.rb, services/comm/config/sidekiq.yml, services/comm/spec/dummy/config/sidekiq.yml, services/iam/config/sidekiq.yml, services/organization/config/sidekiq.yml, services/storage/config/sidekiq.yml
* No ticket
Get rid of queue names except `"#{Settings.service.name}_default"`.
=> Consolidate queues names

lib/core/lib/ros/core/engine.rb, lib/core/lib/ros/prometheus_exporter/middleware.rb
[Services throws an exception when metrics collection enabled](https://perxtechnologies.atlassian.net/browse/PW-1686)
typo fix
=> [hotfix] Fix typo on prometheus_exporter middleware

lib/core/lib/ros/request_logger/fluentd.rb
[HTTP request log to data warehouse](https://perxtechnologies.atlassian.net/browse/PW-1975)
* Flatten HTTP log in preprocessor
* Request response headers transferred as array of hashes that is compatible with BQ schema
Change allow us to process HTTP logs on fluentd and pipe it to BQ warehouse
=> [PW-1975] Flatten http log

.circleci/config.yml
- Added publish test result to circleci
=> [PW-1689] [PW-2131] Add publish test result steps to circleci test job

.circleci/config.yml, services/storage/app/models/tenant.rb
=> Fix storage db seed not working for ROS_ENV test

lib/core/app/models/concerns/ros/application_record_concern.rb, lib/core/app/models/concerns/ros/urn_concern.rb, lib/core/lib/ros/core.rb, lib/core/lib/ros/jwt.rb, lib/core/lib/ros/urn.rb, lib/core/spec/lib/jwt_spec.rb, lib/core/spec/lib/urn_spec.rb, lib/core/spec/shared/models/example_groups.rb
* No ticket
`Ros::Jwt` and `Ros::Urn` were previously located in the `core.rb`. Now it's extracted to it's own external files.
=> Extract Jwt and Urn classes from core to external files

lib/core/app/controllers/concerns/ros/application_controller_concern.rb
* no ticket
Replaced `Ros::Urn.new(*sub_cognito.split(':'))` with `Ros::Urn.from_urn(sub_cognito)`. It does the same but looks nicely.
After merging this we will have more clean code.
=> [Chore] Refactor `authenticate_it!` methods to use `Ros::Urn.from_urn`

lib/core/lib/generators/ros/controller/controller_generator.rb, lib/core/lib/generators/ros/endpoint/endpoint_generator.rb, lib/core/lib/generators/ros/generators_helper.rb, lib/core/lib/generators/ros/model/model_generator.rb, lib/core/lib/generators/ros/model_spec/model_spec_generator.rb, lib/core/lib/generators/ros/resource/resource_generator.rb, lib/core/lib/generators/ros/sdk_endpoint/sdk_endpoint_generator.rb, lib/core/lib/template/controller.yml.erb, services/cognito/lib/ros/cognito/engine.rb, services/comm/lib/ros/comm/engine.rb, services/iam/lib/ros/iam/engine.rb, services/organization/lib/ros/organization/engine.rb
[Refactor endpoint generators](https://perxtechnologies.atlassian.net/browse/PW-2129)
- Create controller generator instead of using invoke(:controller) to avoid generating controller spec
- Update all files generated by ros:endpoint to have `# frozen_string_literal: true"
- Allow ModelGenerator and ResourceGenerator to receive additional full ARGV instead of just the name
- Create SDK endpoint generator
- Update engine files to specific factory directories
Fixed issues raised by Rob in the endpoint generator
=> [PW-2129] refactor endpoint generators

lib/core/app/jobs/ros/application_job.rb, lib/core/app/operations/ros/activity_base.rb, services/comm/spec/operations/event_process_spec.rb, services/comm/spec/operations/message_create_spec.rb
- N/a
- Updated ActivityBase class to return an OperationResult
This provides a standard way for interpreting the results of the operation call
=> [Chore] Activity Base should return an operation result

services/cognito/app/models/user.rb, services/cognito/app/resources/user_resource.rb, services/cognito/db/migrate/20190317073055_create_users.rb, services/cognito/spec/dummy/db/schema.rb, services/cognito/spec/models/user_spec.rb, services/cognito/spec/requests/users_spec.rb
[Allow cognito signup anonymously](https://perxtechnologies.atlassian.net/browse/PW-2209)
- Added anonymous attribute to cognito users
- Ensure the default value for anonymous is set
This allows us to create anonymous users
=> [PW-2209] Allow cognito signup anonymously

services/cognito/doc/schemas/cloud_events/cognito/chown_request.avsc, services/cognito/doc/schemas/cloud_events/cognito/chown_result.avsc
[Create Rspec Shared Context for Cognito user](https://perxtechnologies.atlassian.net/browse/PW-2344)
- Generated some avsc files to fix specs failing on CI
The CI should be passing after this is merged
=> [PW-2344] Fix broken model specs in ros by regenerating avsc files

lib/core/lib/generators/ros/request_spec/request_spec_generator.rb
* No JIRA case for this
- Remove useless `all` context
- `'jsonapi requests'` context included before variables redefined.
Request specs generator is usefull now!
=> [Hotfix] Update request specs generator

.github/workflows/lint_rubocop.yml, .rubocop_todo.yml, lib/core/lib/ros/tenant_middleware.rb
- N/a
- using github action which will use perx rubocop gem
Instead of having the errors logged in the action itself, this will add a comment with the rules being broken
=> [Chore] Using github action with custom gem

lib/core/app/controllers/concerns/ros/application_controller_concern.rb, lib/core/lib/ros/core/engine.rb, lib/core/lib/ros/request_logger/fluentd.rb
[Tenant name and user id need to add in HTTP log data](https://perxtechnologies.atlassian.net/browse/PW-2268)
- Ros::RequestLogger::Fluentd inherits from Rack::Fluentd
- Split parsing of different logging parameters to their methods
- Added iam user id, cognito user id and account id (tenant) to the fluentd logs
This cleans up the ros fluentd logger class and adds the context to the logs.
=> [PW-2268] Tenant name and user id need to add in http log data 

.rubocop_todo.yml, lib/core/lib/ros/prometheus_exporter/middleware.rb, lib/core/spec/rails_helper.rb, services/cognito/app/models/user.rb, services/storage/app/jobs/platform_event_processor.rb, services/storage/app/models/column_map.rb, services/storage/app/models/transfer_map.rb
N/a
- removed redundant cop disable directive from todo
- cleanup all rubocop warnings
After merging this, we have one less block of rubocop infractions to cleanup
=> [Chore] cleaning up rubocop

services/storage/app/controllers/documents_controller.rb, services/storage/app/controllers/images_controller.rb, services/storage/app/models/concerns/has_attachment.rb, services/storage/app/resources/document_resource.rb, services/storage/app/resources/image_resource.rb, services/storage/lib/storage/engine.rb, services/storage/spec/dummy/config/storage.yml
- [Image preview not working for existing survey engagements when user changed the questions.](https://perxtechnologies.atlassian.net/browse/PW-2189)
- [Unable to upload merchant image](https://perxtechnologies.atlassian.net/browse/PW-2302)
- Evaluate if file persisted successfully and if yes, then render the serialized representation of the record, else render an error message.
- Same logic for uploaded documents.
This should fix the image upload problems we've been facing.
=> [PW-2189, PW-2302] Fixes Image Upload and Document Upload

services/cognito/app/resources/user_resource.rb, services/cognito/spec/requests/users_spec.rb
[User is unable to search audience list  based on contact number](https://perxtechnologies.atlassian.net/browse/PW-1783)
- SQLi fixed
- `phone_number` added to filter fields.
After merging this, we will be able to search the audience by phone number.
=> [PW-1783] Search cognito audience list based on contact number

.github/workflows/lint_rubocop.yml, lib/core/app/models/concerns/association_resource.rb, lib/core/lib/ros/api_token_strategy.rb, lib/core/lib/ros/tenant_middleware.rb, lib/core/lib/ros/urn.rb
- N/a
- Fixed rubocop version to avoid random lint errors due to version updates
- Fixed perx-rubocop version to match the versions
improves lint stability
=> Lock rubocop version

services/cognito/app/controllers/metabase_token_controller.rb, services/cognito/spec/requests/metabase_cards_spec.rb, services/cognito/spec/requests/metabase_token_spec.rb
Bugfix for metabase token retrieval error code
- Renders 404 when card not found
=> Metabase token endpoint to return 404 if card not found

services/iam/spec/requests/users_spec.rb
[Role based filtering is not working](https://perxtechnologies.atlassian.net/browse/PW-1674)
- Added group filtering on the user
This allows the api to filter by group id when requesting the users.
=> [PW-1674] Add test coverage for role based filtering

services/cognito/db/seeds/development/tenants.seeds.rb, services/comm/db/seeds/development/tenants.seeds.rb, services/iam/db/seeds/development/tenants.seeds.rb, services/organization/db/seeds/development/tenants.seeds.rb, services/storage/db/seeds/development/tenants.seeds.rb
[update seed files for whistler and ros for all services](https://perxtechnologies.atlassian.net/browse/PW-2768)
- Updated tenant seed files to create Tenant with public schema, and ID 1
=> [PW-2768] update seed files for whistler and ros for all services

services/cognito/app/operations/chown_request_process.rb
[Change ownership of actual outcomes and request outcomes](https://perxtechnologies.atlassian.net/browse/PW-2720)
- Outcome service added to chown operation
After merging this, `ChownResult` will be created for `outcome` service.
=> [PW-2720] Add Chown to outcome service

lib/core/app/operations/ros/operation_result.rb, services/comm/app/models/template.rb, services/comm/app/operations/event_process.rb, services/comm/spec/models/template_spec.rb, services/comm/spec/operations/event_process_spec.rb
[Write tests for PW-1027](https://perxtechnologies.atlassian.net/browse/PW-1909)
- Added tests for template rendering in Comm Service
=> [PW-1909] Write tests for PW-1027

services/comm/app/operations/event_process.rb, services/comm/spec/jobs/event_process_job_spec.rb, services/comm/spec/operations/event_process_spec.rb
- no jira case
- Attribute `params` changed to `id` for event process operation.
After merging this, event process operation will work properly.
=> [Hotfix] Event process operation

services/comm/app/controllers/messages_controller.rb, services/comm/app/operations/message_create.rb, services/comm/app/policies/message_policy.rb, services/comm/spec/operations/message_create_spec.rb, services/comm/spec/requests/messages_spec.rb
[Limit SMS sending to users with appropriate permissions](https://perxtechnologies.atlassian.net/browse/PW-2667)
- Perform checking when creating message and fail if cognito user ID present
=> [PW-2667] Limit SMS sending to users with appropriate permissions

services/iam/app/mailers/account_mailer.rb
[Account mailer to access tenant properties base url for mail](https://perxtechnologies.atlassian.net/browse/PW-2823)
- Fixed way to access the tenant's base url for the email
=> [PW-2823] Account mailer to access tenant properties base url for mail

lib/core/lib/ros/infra/aws/storage.rb, services/storage/app/models/document.rb, services/storage/app/resources/document_resource.rb
return url when uploading a new document
provide a function to create a presigned url
After merging this, a new document (csv) upload will return a presigned url that cna be used to download the document from S3
=> return a presigned url for file downloading

services/cognito/spec/requests/users_spec.rb
- no jira case
- Fix the specs
After merging this, specs will pass not only on December 12.
=> [Hotfix] Cognito user request specs

services/storage/app/controllers/concerns/has_attachment_controller.rb, services/storage/app/controllers/documents_controller.rb, services/storage/app/controllers/images_controller.rb, services/storage/app/models/concerns/has_attachment.rb
2 controllers were implementing their own `model_class` instead of using the broken version in the controller concern. So fix the broken version and use that.
Less redundant code
=> storage: use model_class from controller concern

services/comm/app/models/providers/aws.rb
[Update sns configuration based on new config structure](https://perxtechnologies.atlassian.net/browse/PW-2186)
- Updated code to rely on settings rather than server running mode to decide where to connect
- Rescue SNS service error and logging it
This solves the issues with SMS sending via AWS in the staging cluster that is running in  development mode
=> [PW-2186] Update sns configuration based on new config structure

services/cognito/app/operations/segments/age.rb, services/cognito/app/operations/segments/gender.rb, services/cognito/app/operations/segments_apply.rb, services/cognito/app/resources/user_resource.rb, services/cognito/spec/factories/users.rb, services/cognito/spec/operations/segments/age_spec.rb, services/cognito/spec/operations/segments/gender_spec.rb
[We need 2 more filter, age and gender](https://perxtechnologies.atlassian.net/browse/PW-2895)
- Age segments
- Gender segments
After merging this, we wiil be able to segment audience by gender and age.
=> [PW-2895] Age and gender segments

lib/core/app/models/concerns/association_resource/has_many_resources.rb
fixed `query_resource` method to save `where` state after yield
=> [Fix] Fixed query_resource method

lib/core/app/models/concerns/association_resource/belongs_to_resource.rb, lib/core/spec/support/helpers/association_resource_stub.rb
- No jira case
- TBD
After merging this, TBA
=> [Chore] Update stubbed_resource helper

services/cognito/app/resources/pool_resource.rb, services/cognito/spec/requests/pools_spec.rb
[Support filter pool by system generated](https://perxtechnologies.atlassian.net/browse/PW-3062)
- New filter `system_generated` added to Pools
- Fix SQL Injection vulnerability in `query` filter
After merging this, FE will be able to filter pools by `system_generated` flag.
=> [PW-3062] system_generated filter to pools

lib/core/spec/support/helpers/json_api_helper.rb
[Removing rewards from campaign does not get saved](https://perxtechnologies.atlassian.net/browse/PW-2724)
- Added `deleted_at` as one of the generic attributes for json api spec helper
After merging this, we have ignored deleted_at being sent for create/update params.
=> Add deleted_at column as generic attributes for json api spec helper

lib/core/lib/ros/core.rb, lib/core/lib/ros/core/engine.rb
=> Support configurable config root

services/cognito/spec/dummy/config/database.yml, services/comm/spec/dummy/config/database.yml, services/iam/spec/dummy/config/database.yml, services/organization/spec/dummy/config/database.yml, services/storage/spec/dummy/config/database.yml
[Segmentation Fault when trying to run console](https://perxtechnologies.atlassian.net/browse/PW-3122)
- added gssencode to database.yml. This has been identified as a problem running on osx and adding the gssencode seems to solve the problem. 
REF: https://www.postgresql.org/message-id/93f7379b-2e2f-db0c-980e-07ebd5de92ff%40crunchydata.com
=> [PW-3122] Segmentation Fault when trying to run console

Dockerfile
=> fix issue with bundler 2.1.2 and update os image to buster

lib/core/app/models/concerns/association_resource/resource_helper.rb
[Does not work include tiers in the loyalty cards](https://perxtechnologies.atlassian.net/browse/PW-3234)
- Returning proper type when polymorphic association
It should fix the includes for polymorphic associations
=> [PW-3234] Fix include polymorphic relationships

lib/core/app/jobs/ros/application_job.rb, services/cognito/app/resources/endpoint_resource.rb, services/comm/app/operations/event_process.rb, services/comm/app/operations/message_create.rb, services/comm/spec/operations/message_create_spec.rb, services/comm/spec/requests/messages_spec.rb
-N/a
- Updated timezone of workers to temporarily default to SGP
- Relax SMS sending permissions
After this has been merged, it should fix the event enqueuing and the sms sending
=> [Hotfix] Fix event creation
