rails-on-services/ros

lib/core/app/controllers/concerns/ros/application_controller_concern.rb, services/iam/app/models/tenant.rb, services/iam/app/resources/user_resource.rb, services/iam/spec/dummy/config/application.rb, services/iam/spec/factories/policies.rb, services/iam/spec/factories/users.rb, services/iam/spec/policies/policy_policy_spec.rb, services/iam/spec/requests/users_spec.rb
This mostly excludes `jwt_payload` from creatable and updatable fields for IAM users
It adds the first request spec for getting the index and posting to create users.
=> [Resolves PW-780 & PW-781] IAM users crash

lib/sdk/lib/ros_sdk/models/comm.rb, services/cognito/Gemfile.lock, services/comm/Gemfile.lock, services/comm/app/models/event.rb, services/comm/app/models/providers/aws.rb, services/comm/app/models/template.rb, services/comm/app/resources/event_resource.rb, services/comm/app/resources/template_resource.rb, services/comm/db/migrate/20190905024214_move_campaign_id_to_campaign_entity_id.rb, services/comm/db/migrate/20190905031621_move_campaign_id_to_campaign_entity_id_in_event.rb, services/comm/db/seeds/development/data.seeds.rb, services/comm/lib/ros/comm/engine.rb, services/comm/spec/dummy/config/environments/test.rb, services/comm/spec/dummy/db/schema.rb, services/comm/spec/factories/events.rb, services/comm/spec/factories/templates.rb, services/comm/spec/factories/user.rb, services/comm/spec/models/campaign_spec.rb, services/comm/spec/requests/events_spec.rb, services/comm/spec/requests/templates_spec.rb, services/iam/lib/ros/iam/engine.rb, services/organization/Gemfile.lock
After this, the Templates and Events will be related with the Campaign service's Entity instead of the local service campaign.
This also allows us to create templates and events.
Some basic request specs have been written.
=> [Hotfix] Allow Comm to create Templates and Events

lib/core/app/controllers/concerns/ros/application_controller_concern.rb, lib/core/app/models/policy_user.rb
No JIRA issue
- Created PolicyUser class that contains a reference to the iam user as well as the cognito_user_id when this is defined. This class also supports additional params in case we want to do scoped decisions.
Once this is merged, the pundit user, instead of being simply an IAM user will be a reference to an instance of the class PolicyUser, which internally has the IAM user and the cognito_user_id.
=> [Resolves] Add cognito user id to controller concern context

lib/core/spec/shared/models/example_groups.rb
[RSpec Shared Examples for Core Application Record Concern](https://perxtechnologies.atlassian.net/browse/PW-1309)
New shared examples group created for models
Now we should use this shared examples in all model specs:
```ruby
RSpec.describe Something, type: :model do
include_examples 'application record concern' do
let(:tenant) { Tenant.first }
let!(:subject) { create(factory_name) }
end
end
```
=> [PW-1309] Shared examples for models

lib/core/spec/shared/models/example_groups.rb
Adjust the way how `factory_name` generated
Previously the `factory_name` was generated incorrectly for `ModelsLikeThis` => `:modelslikethis`
Now it's `:models_like_this`
=> [hotfix] adjust factory_name

services/iam/Gemfile.lock, services/iam/app/policies/tenant_policy.rb, services/iam/app/resources/tenant_resource.rb
[Endpoint for getting the current tenant properties before sign-in](https://perxtechnologies.atlassian.net/browse/PW-1356)
- Updated Tenant Policy to scope the requests to requester's tenant id
- Updated `properties` to `display_properties`
After merging this, requests to tenant's endpoints will be scoped to the requestor's tenant id. It also updates the display properties to be serialised instead of properties, since we've agreed that properties would be used for internal behaviour while display properties would be used for external data (namely front end requirements)
=> [PW-1356] Endpoint for getting the current tenant properties before sign-in

lib/core/spec/shared/models/example_groups.rb, services/cognito/spec/factories/endpoints.rb, services/cognito/spec/models/endpoint_spec.rb, services/cognito/spec/models/identifier_spec.rb, services/cognito/spec/models/pool_spec.rb, services/cognito/spec/models/tenant_spec.rb, services/cognito/spec/models/user_pool_spec.rb, services/cognito/spec/models/user_spec.rb, services/comm/spec/models/campaign_spec.rb, services/comm/spec/models/event_spec.rb, services/comm/spec/models/message_spec.rb, services/comm/spec/models/provider_spec.rb, services/comm/spec/models/template_spec.rb, services/iam/spec/models/root_spec.rb, services/iam/spec/models/user_spec.rb, services/organization/spec/models/branch_spec.rb, services/organization/spec/models/org_spec.rb
[RSpec Shared Examples for Core Application Record Concern](https://perxtechnologies.atlassian.net/browse/PW-1309)
All model specs are now include shared example groups from ApplicationRecordConcern.
No new model specs were added in this PR, only existing were refactored.
There's also no shared examples for the Storage service yet because I'm working on specs for this service on another branch `storage_request_specs`.
Model specs are now unified and more robust.
=> [PW-1309] Apply shared examples to core model specs

lib/core/spec/shared/requests/example_groups.rb
- Created rspec shared context to log in as cognito user 
This shared example is needed as when a user posts a new survey answer/game transaction, the model resource tries to grab the `cognito_user_id` which is stored in the JWT token. If the `user_id` isn't here, the response fails and user_id is a compulsory field on the model.
=> [PW-1351] Create Rspec Shared Context for Cognito user

lib/core/lib/generators/ros/request_spec/request_spec_generator.rb, lib/core/spec/support/helpers/api_json_helper.rb, lib/core/spec/support/helpers/json_api_helper.rb, lib/core/spec/support/load_helpers.rb, services/comm/spec/requests/events_spec.rb, services/comm/spec/requests/templates_spec.rb
[Extract json api as a lib core spec helper method](https://perxtechnologies.atlassian.net/browse/PW-1539)
- Extract `json_api` as a lib core spec helper method
- Remove places where `json_api` is defined
Makes our code more DRY. Developers don't have to define `json_api` in their request specs everytime.
=> Pw 1539 extract json api as a lib core spec helper method

lib/core/config/settings.yml, lib/core/lib/ros/cloudevents/fluentd_avro_logger.rb, lib/core/lib/ros/core/engine.rb
This PR allow the avro logger to use HTTP protocol to send cloud event records to fluentd.
=> [PW-1635] Modify fluentd_avro_logger to support HTTP transport

.circleci/config.yml
- Changed circleci config to retry push docker image when there's an error (added retry)
=> Fix circleci push timeout

lib/core/app/controllers/concerns/ros/application_controller_concern.rb, lib/core/app/models/policy_user.rb, lib/core/app/policies/ros/application_policy.rb, services/iam/spec/policies/policy_policy_spec.rb
[Can't perform actions with basic root token](https://perxtechnologies.atlassian.net/browse/PW-1638)
- moved the checking if the user is root to the policy user class and using that logic to override the policy checks. We've added this PolicyUser class that keeps information about the iam user and cognito user id, as well as the parms passed in the context. Pundit uses this class as the user context instead of simply the auth'd user. This was causing the logic in the policy to fail because root users do not have attached policies and we were trying to check for it.
After merging this, requests coming from a root are always authorised without checking for policies as a root user should have access to the whole platform. After merging this, there is still a [pending …
=> [PW-1638] Can't perform actions with basic root token

lib/core/lib/generators/ros/request_spec/request_spec_generator.rb, lib/core/spec/support/helpers/json_api_helper.rb, services/comm/spec/requests/events_spec.rb, services/comm/spec/requests/templates_spec.rb
- No Ticket
**This introduces breaking changes in the `jsonapi_data` spec helper**
- No longer using remove attribute as true/false to combine with expanding arguments. This has been replaced with params passed as options, providing a much clear method signature.
Previously `jsonapi_data` signature was:
```ruby
jsonapi_data(model, true, :params, :to, :exclude)
``` 
Now replaced with:
```ruby
jsonapi_data(model, extra_attributes: { invalid: :param }, skip_attributes [:params, :to, :exclude], method: :put )
```
- default `method` will be `:get` and no changes will be made to the final JSON api data.
- if `:put` or `:patch` are passed, the helper will automatically inject the `id` in the JSON api data.
- `extra_attributes` hash can be used for adding key/values to the JSON api data
- …
=> Refactor jsonapi data spec helper

services/comm/app/models/event.rb, services/comm/app/resources/event_resource.rb, services/comm/spec/factories/events.rb, services/comm/spec/models/event_spec.rb, services/comm/spec/models/message_spec.rb, services/comm/spec/requests/events_spec.rb
[Can't save a campaign without an audience](https://perxtechnologies.atlassian.net/browse/PW-1879)
- cleanup event model class to follow the order in our pattern
- event resource allows pool_id to be passed and transforms that into a "Ros::Cognito::Pool"
- before save ensures a provider is set. This should be updated to match the tenant's default provider.
This allows the api to create an event with the proper target set.
=> [PW-1879] Can't save a campaign without an audience

lib/core/lib/generators/ros/request_spec/request_spec_generator.rb, lib/core/spec/shared/models/example_groups.rb, services/comm/spec/requests/events_spec.rb, services/comm/spec/requests/templates_spec.rb, services/iam/spec/requests/tenants_spec.rb, services/iam/spec/requests/users_spec.rb
* No ticket
Remove all redundant `tenant.switch` from specs
We don't need to explicitly switch anymore, everything is automatic after [@412252e](https://github.com/rails-on-services/ros/tree/412252e69596b381511ce04460bb4694c3c9e527)
=> update all specs to remove redundant `tenant.switch`

lib/core/app/models/concerns/association_resource/association_interface.rb, lib/core/app/models/concerns/association_resource/belongs_to_resource.rb, lib/core/spec/support/helpers/json_api_helper.rb
- fixed association helpers `@model.resource(:resource_name)`
- added `relationships` support to jsonapi_data rspec helper
=> Fix association resource helpers

lib/core/app/models/concerns/association_resource/belongs_to_resource.rb
fixed call of `_resource_class` for `belongs_to_resource` associations if `class_name` not given or not exists
=> fixed _resource_class calling without class_name presented

lib/core/ros-core.gemspec
[Unsuccessful request aren logged by application](https://perxtechnologies.atlassian.net/browse/PW-2104)
Sergey's PR been merged into [rack-fluentd-logger](https://github.com/mikhailvs/rack-fluentd-logger)
So bump gem version to receive an update
Tested that non-2xx requests are logged now and pushed to BQ warehouse
=> [PW-2104] Bump rack-fluentd-logger version

services/iam/app/resources/user_resource.rb
[Role based filtering is not working](https://perxtechnologies.atlassian.net/browse/PW-1647)
- Added groups to allowed filters in the resources 
After merging this, we allow IAM users to be filtered by groups. The tests are being covered in #96 which are waiting for another PR to be merged
=> [PW-1647] Role based filtering is not working

services/cognito/app/policies/tenant_policy.rb, services/cognito/app/policies/user_policy.rb, services/cognito/spec/policies/user_policy.rb, services/cognito/spec/policies/user_policy_spec.rb
[Profile Service to Fetch cognito users not returning in correct format](https://perxtechnologies.atlassian.net/browse/PW-2098)
- Created TenantPolicy for cognito user that includes the shared tenant policy from core
- Created UserPolicy that scopes the results based on the cognito user id that the scope has. This is implemented as a temporary solution so the front end can query info about the token owner. With the implementation of policies there would be a specific endpoint to fetch and update info about the token owner.
Once this is merged, tenants and users will be scoped in the cognito service based on the context set by the token.
=> [PW-2098] Profile Service to Fetch cognito users not returning in correct format

lib/core/app/models/concerns/association_resource/belongs_to_resource.rb, lib/core/app/models/concerns/association_resource/has_many_resources.rb
Gives ability to `:belongs_to_resource` and `:has_many_resources` which could be polymorphic, to accept `ActiveRecord` models
=> AssociationResource ActiveRecord support

services/cognito/app/resources/user_resource.rb, services/cognito/spec/requests/users_spec.rb
[Search functionality returning incorrect results when searching based on user id](https://perxtechnologies.atlassian.net/browse/PW-1779?atlOrigin=eyJpIjoiODI0MmM0MjE5Mjc5NDgyN2FmMGY3M2VjY2EyNjVkNTEiLCJwIjoiaiJ9)
- Perform a check to see if query string is digits only, and if yes, query by ID. Else, perform a query based on other attributes such as primary_identifier, first_name etc.
- This should return more accurate results and removes list of redundant info when query by ID.
=> [PW-920] Search functionality returning incorrect results when searching based on user id.

.github/workflows/lint_rubocop.yml, services/organization/spec/models/org_spec.rb
- N/a
- Created GitHub workflow to run rubocop lint on Push
1. This allows us to have the rubocop listing separated from the CircleCI running the tests.
2. Currently Core and SDK because they are 'loaded as gems' they are not being lint while running `ros be test` because this depends on the service to be built.
=> [Chore] Use GitHub actions for rubocop lint

services/cognito/spec/requests/users_spec.rb
[Failing Test](https://perxtechnologies.atlassian.net/browse/PW-1779)
- Test was previously failing because a User with the random ID was actually present in the Users pool
- Expected result: User with the random ID SHOULD NOT be present, to test cases where zero results should be returned when querying for ID which is not in the database.
- Fix applied: Users in the pool are sorted in ascending ID and the random ID is an increment of the last User ID. (which means a non-existent user)
=> PW-920: Fix Failing Test

services/cognito/app/resources/user_resource.rb, services/cognito/spec/requests/users_spec.rb
[Search functionality returning incorrect results when searching based on user id.](https://perxtechnologies.atlassian.net/browse/PW-1779)
Specified table in SQL query when querying for an ID.
This address the ambiguous column error raised because current SQL query only passes in ID, without specifying the table to perform the query on.
=> [PW-1779] Search functionality returning incorrect results when searching based on user id.

services/cognito/app/resources/pool_resource.rb, services/cognito/spec/requests/pools_spec.rb
[Audience List search filter don't work](https://perxtechnologies.atlassian.net/browse/PW-1877)
- Handles query by name and ID, when filter[query] sent to endpoint
This allows audience list to be filtered by ID and name. Currently only ID filtering works.
=> [PW-1877] Audience List search filter don't work

lib/core/app/controllers/concerns/ros/application_controller_concern.rb, lib/core/lib/ros/core/engine.rb
[Add sentry gem to our backend and configure it properly](https://perxtechnologies.atlassian.net/browse/PW-2459)
- Checking for Sentry Env var set to require it in engine init.
- Setting context if sentry env set
This enables Sentry in our services if the env var is defined
=> [PW-2459] Add sentry gem to our backend and configure it properly

.rubocop.yml, lib/core/app/models/concerns/ros/urn_concern.rb, lib/core/lib/ros/api_token_strategy.rb, lib/core/lib/ros/urn.rb, services/iam/app/controllers/concerns/is_tenant_scoped.rb, services/iam/app/controllers/credentials_controller.rb, services/iam/app/models/credential.rb, services/iam/app/models/root.rb, services/iam/app/models/user.rb, services/iam/app/operations/blackcomb_user_create.rb, services/iam/app/resources/credential_resource.rb, services/iam/app/resources/root_resource.rb, services/iam/config/routes.rb
[Define how a root user should create an app token for a specific tenant](https://perxtechnologies.atlassian.net/browse/PW-2434)
- Added ability to create credentials for a root user, using the root token
This allows a request with a platform owner root token to create a credential for a tenant's root account. This completes the flow for blackcomb tenant agnostic deploy
=> [PW-2434] define how a root user should create an app token for a specific tenant

services/cognito/app/resources/user_resource.rb, services/cognito/db/migrate/20191129055605_add_birthday_to_user.rb, services/cognito/doc/schemas/cloud_events/cognito/metabase_card.avsc, services/cognito/doc/schemas/cloud_events/cognito/user.avsc, services/cognito/spec/dummy/db/schema.rb, services/cognito/spec/requests/users_spec.rb
[Implement a birthday worker](https://perxtechnologies.atlassian.net/browse/PW-2612)
- Add `birthday` column to cognito user
- Create `birth_day` and `birth_month` filters to cognito user resource
After merging this, we will be able to save birthday for cognito user and filter users by their birth day or month using any date or timestamp:
`?filter[birth_day]=2019-12-01T05:22:08` or `?filter[birth_day]=2019-12-01` matches to `1990-12-01`, `1983-12-01` etc.
`?filter[birth_month]=2019-12-06T05:22:08` or `?filter[birth_month]=2019-12-31` matches to `1991-12-21`, `2001-12-04` etc.
=> [PW-2612] Birthday worker

services/iam/app/controllers/iam/confirmations_controller.rb, services/iam/app/controllers/iam/passwords_controller.rb, services/iam/spec/requests/users/confirmation_spec.rb, services/iam/spec/requests/users/password_spec.rb
[current forgot password api is way to talkative for an api that works without authentication](https://perxtechnologies.atlassian.net/browse/PW-2785)
- Returns simple ok response for confirmations and password endpoints in IAM
=> [PW-2785] current forgot password api is way to talkative for an api that works without authentication

lib/core/spec/shared/jobs/operation_job.rb
- no jura case
- Shared example created to test operation jobs.
After merging this, we will able to test jobs in 1 line:
```ruby
RSpec.describe SomeJob, type: :job do
include_examples 'operation job'
end
```
Or if job has arguments:
```ruby
RSpec.describe AnotherJob, type: :job do
include_examples 'operation job' do
let(:with_arguments) { { param1: :value } }
end
end
```
=> [Chore] Shared examples for operation job specs

services/cognito/app/models/user.rb, services/cognito/app/resources/user_resource.rb, services/cognito/db/migrate/20191205023159_add_gender_to_user.rb, services/cognito/doc/schemas/cloud_events/cognito/user.avsc, services/cognito/spec/dummy/db/schema.rb, services/cognito/spec/models/user_spec.rb
[User gender and age (DOB) Information required ](https://perxtechnologies.atlassian.net/browse/PW-2559)
- User gender added as an enum attribute with values `male, female, other`.
After merging this, cognito user will have a gender attribute.
=> [PW-2559] Add gender column to cognito user

services/cognito/app/resources/pool_resource.rb, services/cognito/spec/requests/pools_spec.rb
[Do not fetch the list of users to display the number of users in audiences table](https://perxtechnologies.atlassian.net/browse/PW-2721)
- Added users_count attr in resource, for front end to display
- Front end no longer has to include_users in pools endpoint query, to count and display users count
=> [PW-2721] Do not fetch the list of users to display the number of users in audiences table

services/iam/app/controllers/users/sessions_controller.rb, services/iam/spec/requests/users/authentication_spec.rb
[Unconfirmed users should not be able to login](https://perxtechnologies.atlassian.net/browse/PW-2839)
- added `confirmed?` check for IAM usrs's before login
=> [PW-2839 ] Check user is confirmed before login

lib/core/lib/ros/infra.rb
By default ros-cli will write out config for mq and storage and the `infra.rb` loader doesn't care if they have been enabled but only if there is configuration.
As a consequence, ros will try to load mq even if not explicitly enabled causing things to blow up as `aws-sdk-sqs` is not included in core.
Check if we are explicitly enabled before loading mq.
Due to the way we build the containers, the `aws-sdk-sqs` gem was being included everywhere thus hiding the problem. The workaround mentioned in #150 is now no longer needed.
=> core: only load mq/storage if explitly enabled

lib/core/app/models/concerns/ros/application_record_concern.rb
[Modify Ros::ApplicationRecordConcern to include record operation as part of the cloud event data](https://perxtechnologies.atlassian.net/browse/PW-2899)
- Using transaction_include_any_action?([action]) to identify trigger and merge in cloud_event_data
- Should be able to have a field called _op with the type of trigger of an after_commit transaction
=> [PW-2899] Modify Ros::ApplicationRecordConcern to include record operation as part of the cloud event data

lib/core/lib/generators/avro/avro_builder.rb
[Modify avro schema generator to include an optional field `_op`](https://perxtechnologies.atlassian.net/browse/PW-2900)
- Add optional attribute _op to Avro Builder
=> [PW-2900] Modify avro schema generator to include an optional field `_op`

services/cognito/config/routes.rb, services/cognito/spec/dummy/config/routes.rb
N/a
- Moved route to the engine instead of spec dummy app. This is because the engine is mounted and therefore it fails to find the path when we run it locally.
This fixes the route finding when running locally
=> [Hotfix] Fixed cognito route

lib/core/spec/shared/models/example_groups.rb
We expect the factory not to blow up - not that it doesn't blow up with a certain error.
=> core: rspec rightfully warns that we are too fixated on KeyError

lib/core/Gemfile.lock, lib/core/ros-core.gemspec, lib/core/spec/dummy/db/schema.rb, lib/core/spec/lib/urn_spec.rb, lib/core/spec/rails_helper.rb, lib/core/spec/validators/json_schema_validator_spec.rb, services/cognito/Gemfile.lock, services/comm/Gemfile.lock, services/iam/Gemfile.lock, services/organization/Gemfile.lock, services/storage/Gemfile.lock
Properly load the dummy app and add missing dependency to allow running the core specs.
urn specs are still failing though.
=> core: enable running specs

lib/core/app/jobs/ros/chown_job.rb
- somehow related to [Update end to end test 'anonymous flow game play' to include fetching of campaign](https://perxtechnologies.atlassian.net/browse/PW-3044)
- [uninitialized constant Ros::Chown Did you mean? Ros::ChownJob](https://sentry.io/organizations/perx-technologies-pte-ltd/issues/1413098443/?environment=production-uat-dev1&project=1819291&query=is%3Aunresolved&statsPeriod=24h)
- `operation_class` was deleted from `Ros::ChownJob` during optimization, but it's need to be there, because `Ros::ChownJob` running operations in different services.
After merging this, we will have `chown` works again.
=> [Hotfix] put operation_class back to Ros::ChownJob

lib/core/lib/generators/ros/integration_test/integration_test_generator.rb, lib/core/lib/template/integration_test.yml.erb, lib/core/lib/template/locust_endpoint.yml.erb, sre/lib/base/helper.py, sre/lib/cognito/chown_request.py, sre/lib/cognito/pool.py, sre/lib/cognito/user.py, sre/lib/iam/user.py, sre/lib/organization/org.py
[Create load test for daichi workflow](https://perxtechnologies.atlassian.net/browse/PW-3025)
- Updated `IntegrationTestGenerator` to be a named based generator
- Updated `integration_test.yml` to use setup instead of on start
- Updated `locust_endpoint.yml.erb` to support update method
- Shift endpoints in individual services from helper file to their own folders 
To generate the 
Provide methods to support the daiichi load test work flow on whistler
To generate integration test files in the future, you can run
`rails g ros:integration_test scenario_name`
=> Pw 3025 create load test for daichi workflow

services/storage/spec/dummy/config/storage.yml
If localstack is not available or buckets are misconfigured when running the tests, the storage tests will wait for timeouts before continuing due to tenant changes causing a writeout (and subsequent upload) of `users.conf`.
Instead, have ActiveStorage simply store to disk.
=> storage: do not depend on localstack when running tests

services/cognito/app/operations/pool_create.rb, services/cognito/app/operations/segments/age.rb, services/cognito/app/operations/segments_apply.rb, services/cognito/spec/operations/pool_create_spec.rb, services/cognito/spec/operations/segments/age_spec.rb, services/cognito/spec/operations/segments/birthday_spec.rb, services/cognito/spec/operations/segments/except_ids_spec.rb, services/cognito/spec/operations/segments/gender_spec.rb, services/cognito/spec/operations/segments_apply_spec.rb, services/storage/spec/requests/files_spec.rb
[Valid campaign created is stuck at scheduled status for more than half an hour](https://perxtechnologies.atlassian.net/browse/PW-3165)
- If final pool is empty, create it anyway
- If apply segment fails, then return a failed operation with no users
- Updated test coverage
- Fixed typos
After this has been merged we are mostly allowing pools to be created even if no users match the segments passed. It also checks operation results to ensure that if any of the operation fails, then no unexpected errors are raised.
=> [PW-3165] Valid campaign created is stuck at scheduled status for more than half an hour

services/comm/app/operations/event_process.rb, services/comm/app/resources/message_resource.rb
- N.a
- Re-enable SMS sending when processing events
- Defaulting SMS being sent by AWS provider
This gets us one step closer to a better sms sending.
=> [Chore] Renable sms sending from event process

lib/core/lib/generators/avro/avro_builder.rb
- No Jira case
- Avro builder updated.
After merging this, we will have type `string` in avro schemas for all decimal columns.
=> [Hotfix] Avro Builder to cast decimal as string

lib/core/app/models/concerns/ros/application_record_concern.rb
This fixes the avro data type for BigDecimal, we are generating avro schema as string.
=> Fix avro BigDecimal convert to string

lib/core/spec/support/helpers/association_resource_stub.rb, lib/sdk/lib/ros_sdk/sdk.rb
On `stubbed_resource` also stub `with_params`.
=> core: also stub with_params

lib/core/Gemfile.lock, lib/core/lib/ros/scheduler/tenant_handler.rb, lib/sdk/Gemfile.lock, lib/sdk/lib/ros_sdk/sdk.rb, lib/sdk/ros_sdk.gemspec, lib/sdk/spec/ros_sdk/sdk_spec.rb, lib/sdk/spec/spec_helper.rb
[Use RequestStore to store user credential instead of class attributes](https://perxtechnologies.atlassian.net/browse/PW-3145)
- Use RequestStore to store user credential Instead class attributes, so that the credential is properly binding the incoming request.
After merging this, we should not have any issue where the tenant is not reflecting each other in each service.
=> PW-3145: Use RequestStore to store user credential 

lib/core/app/resources/ros/application_resource.rb
[Make the ilike filter more flexible](https://perxtechnologies.atlassian.net/browse/PW-3415)
- override `apply_filter` JSONAPI Resources to handle `ilike: true` option. This is [documented feature](https://jsonapi-resources.com/v0.10/guide/resources.html#Applying-Filters).
Example:
```ruby
class SomeResource < ApplicationResource
filter :column_name, ilike: true
end
```
NOTE: Works only with `filter`, not `filters`
After merging this, we will be able to use advanced ilike filter on any resource that inherits from `Ros::ApplicationResource`
=> [PW-3415] ilike filter

services/iam/app/resources/tenant_resource.rb
[Allow IAM tenant to accept properties field](https://perxtechnologies.atlassian.net/browse/PW-3338)
- Add `properties` field to tenant resource for IAM
After merging this, the user should be able to set the `properties` field when creating a new tenant on IAM service.
=> Allow IAM tenant to accept properties field
